---
# 定时执行
name: Cron
on:
  push:
    branches:
      - '**'
    pull_request:
  schedule:
# 需要注意在main分支生效
#    每4分钟执行一次- 注：触发的程序策略是发送当前时间内五分钟的数据-主要考虑发帖频率没那么大，另外多发比少发数据好
    - cron: '*/4 * * * *'


jobs:
  run:
    name: run ${{matrix.go}}
    runs-on: [ubuntu-latest]
    environment:
      name: fei_shu_bot_webhook_url  # Settings -> Environments ->
      # fei_shu_bot_webhook_url: https://github.comxxxx
    strategy:
      fail-fast: false
      matrix:
        go: [
          "1.18",
        ]

    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: ${{matrix.go}}

      - name: run
        env:
          FEI_SHU_BOT_WEBHOOK_URL: ${{ secrets.fei_shu_bot_webhook_url }}
          DURATION_SEC: ${{ vars.DURATION_SEC }}
        run: |
          echo $DURATION_SEC
          go run main.go